language: node_js
node_js:
- 7.7.1
cache:
  directories:
  - $HOME/.yarn-cache
  - node_modules
notifications:
  email: false
script:
- export COMMITTER_EMAIL="$(git log -1 $TRAVIS_COMMIT --pretty="%cE")"
before_deploy:
- ./scripts/setup.sh
deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    branch: master
    condition: "$COMMITTER_EMAIL != $DEVOPS_EMAIL"
after_deploy:
- ./scripts/push.sh
